[versions]
# project modules version
p-root = "2.1.3-dev"
p-honoka-utils = "1.1.2"
p-honoka-kotlin-utils = "1.1.3-dev"
p-honoka-spring-boot-starter = "1.0.4-dev"

# gradle plugins version
gp-honoka-basic = "1.0.2"

# dependencies version
d-hku-honoka-utils = "1.1.2"
d-hsbs-honoka-kotlin-utils = "1.1.3-dev"
d-kotlin = "2.2.0"
d-kotlin-coroutines = "1.10.2"
d-lombok = "1.18.38"
d-spring-boot = "3.5.4"
d-mybatis-plus = "3.5.12"

[plugins]
honoka-basic = { id = "de.honoka.gradle.plugin.basic", version.ref = "gp-honoka-basic" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "d-kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "d-kotlin" }
kotlin-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "d-kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "d-kotlin" }

[libraries]
hku-honoka-utils = { module = "de.honoka.sdk:honoka-utils", version.ref = "d-hku-honoka-utils" }
hsbs-honoka-kotlin-utils = { module = "de.honoka.sdk:honoka-kotlin-utils", version.ref = "d-hsbs-honoka-kotlin-utils" }
mybatis-plus = { module = "com.baomidou:mybatis-plus-spring-boot3-starter", version.ref = "d-mybatis-plus" }
mybatis-plus-jsqlparser = { module = "com.baomidou:mybatis-plus-jsqlparser", version.ref = "d-mybatis-plus" }
slf4j-api = "org.slf4j:slf4j-api:2.0.17"
logback = "ch.qos.logback:logback-classic:1.5.18"
