[versions]
# project modules version
p-root = "2.1.5-dev"
p-honoka-utils = "1.1.3-dev"
p-honoka-kotlin-utils = "1.1.4-dev"
p-honoka-spring-boot-starter = "1.0.5-dev"
p-honoka-android-utils = "1.1.3-dev"

# gradle plugins version
gp-honoka-basic = "1.0.3"

# dependencies version
d-kotlin = "2.2.0"
d-kotlin-coroutines = "1.10.2"
d-lombok = "1.18.42"
d-honoka-utils = "1.1.3-dev"
d-honoka-kotlin-utils = "1.1.4-dev"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "d-kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "d-kotlin" }
kotlin-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "d-kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "d-kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "d-kotlin" }
honoka-basic = { id = "de.honoka.gradle.plugin.basic", version.ref = "gp-honoka-basic" }

[libraries]
honoka-utils = { module = "de.honoka.sdk:honoka-utils", version.ref = "d-honoka-utils" }
honoka-kotlin-utils = { module = "de.honoka.sdk:honoka-kotlin-utils", version.ref = "d-honoka-kotlin-utils" }
